doctrine:
    dbal:
        charset: utf8mb4
        unix_socket: '/Applications/MAMP/tmp/mysql/mysql.sock'
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '8.0.20'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: false
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Entity'
                prefix: 'App\Domain\Entity'
                alias: App