jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
    metadata:
        auto_detection: false
        directories:
            valueobject:
                namespace_prefix: "App\\Domain\\Event"
                path: "%kernel.project_dir%/src/Application/Product/Config/Serializer/Event"
            entity:
                namespace_prefix: "App\\Domain\\Entity"
                path: "%kernel.project_dir%/src/Application/Product/Config/Serializer/Entity"
